project_id = "nltdspmkogjsnnywqzke"

[functions.get-daily-set]
verify_jwt = false

[functions.create-player]
verify_jwt = false

[functions.update-player-name]
verify_jwt = false

[functions.save-run]
verify_jwt = false

[functions.join-group]
verify_jwt = false

[functions.create-group]
verify_jwt = false

[functions.get-my-groups]
verify_jwt = false

[functions.get-leaderboard]
verify_jwt = false

[functions.get-player-run]
verify_jwt = false

[functions.verify-answer]
verify_jwt = false
