// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nltdspmkogjsnnywqzke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sdGRzcG1rb2dqc25ueXdxemtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5MTA5NjQsImV4cCI6MjA4NDQ4Njk2NH0.Q7uC3tJEB-sbaUimtqp2w9__VH2P67-UjtAKexdjmCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});